/**
 * Help screen: full keyboard shortcut reference for the TUI.
 */
export function buildHelpText(): string {
  return [
    "┌─ search-cli Help ──────────────────────────── [q] close ─┐",
    "│                                                           │",
    "│  NAVIGATION                                              │",
    "│    ↑ ↓ / j k     Move selection                         │",
    "│    Enter / o      Open repo in browser                   │",
    "│    /              Focus search input                     │",
    "│    t              Toggle search / trending               │",
    "│    ? / Ctrl+H     Toggle this help screen                │",
    "│    q              Quit                                   │",
    "│                                                           │",
    "│  SEARCH MODE                                             │",
    "│    s              Cycle sort: best-match → stars → ...  │",
    "│    l              Cycle limit: 10 → 25 → 50 → 100       │",
    "│    r              Refresh / re-run last search           │",
    "│    g              Toggle activity graph fullscreen       │",
    "│    Tab            Auto-complete qualifier                │",
    "│                                                           │",
    "│  TRENDING MODE                                           │",
    "│    1-5            Switch tab: Today → Week → Month → ...│",
    "│    ← → / h l     Navigate tabs                           │",
    "│    r              Refresh                                 │",
    "│                                                           │",
    "│  SEARCH SYNTAX                                           │",
    "│    keywords       Free-text search                       │",
    "│    key:value      Qualifier filter                       │",
    "│    -key:value     Negated qualifier                      │",
    "│    \"phrase\"      Exact phrase match                     │",
    "│                                                           │",
    "│  QUALIFIERS                                              │",
    "│    language:  Stars:    Fork:     Archived:  Topic:      │",
    "│    user:      Org:      Repo:     Updated:   Pushed:     │",
    "│    visibility: License: Created:  Size:      In:         │",
    "│                                                           │",
    "│  RATE LIMITS                                             │",
    "│    No token       10 req/min                            │",
    "│    GITHUB_TOKEN   30 req/min (or your plan limit)        │",
    "│                                                           │",
    "│  Set GITHUB_TOKEN in your environment or add to config.  │",
    "└───────────────────────────────────────────────────────────┘",
  ].join("\n");
}
